# Generated by Django 3.2.21 on 2023-09-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigne_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
